"""Notebook template generators for each integration pattern.

For the ADLS/Volume pattern the source is a UC Volume, not external ADLS.
The ingest notebook reads from /Volumes/... and writes to a Delta bronze table.
"""

from src.config_models import IntegrationConfig


def _header(title: str, config: IntegrationConfig) -> str:
    return f"""# Databricks notebook source
# MAGIC %md
# MAGIC # {title}
# MAGIC
# MAGIC **Pattern:** {config.pattern_name}
# MAGIC **Target Table:** `{config.target_full_name}`
# MAGIC **Generated by:** Integration Pattern Accelerator
# MAGIC
# MAGIC > Edit configuration values below before running in production.

# COMMAND ----------

"""


def generate_ingest_notebook(config: IntegrationConfig) -> str:
    """Generate 01_ingest_to_bronze.py content."""
    header = _header("01 - Ingest to Bronze", config)

    if config.pattern_id == "adls_to_bronze":
        vs = config.volume_source
        fmt = vs.file_format if vs else "csv"
        src_vol_path = config.source_volume_path or "/Volumes/catalog/schema/source_volume"
        return header + f'''# DBTITLE 1,Configuration
CATALOG = "{config.catalog_name}"
TARGET_SCHEMA = "{config.target_schema}"
TABLE = "{config.target_table}"
FULL_TABLE = f"{{CATALOG}}.{{TARGET_SCHEMA}}.{{TABLE}}"

# Source: UC Volume containing raw files
SOURCE_VOLUME_PATH = "{src_vol_path}"
FILE_FORMAT = "{fmt}"

# COMMAND ----------

# DBTITLE 1,Set up target schema
spark.sql(f"USE CATALOG {{CATALOG}}")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {{TARGET_SCHEMA}}")

# COMMAND ----------

# DBTITLE 1,Option A: COPY INTO (recommended for production)
# COPY INTO is idempotent — it only loads new files not yet ingested.
# Uncomment this cell and skip Option B for production use.

# spark.sql(f"""
#   COPY INTO {{FULL_TABLE}}
#   FROM '{{SOURCE_VOLUME_PATH}}'
#   FILEFORMAT = {{FILE_FORMAT.upper()}}
#   FORMAT_OPTIONS ('header' = 'true', 'inferSchema' = 'true')
#   COPY_OPTIONS ('mergeSchema' = 'true')
# """)

# COMMAND ----------

# DBTITLE 1,Option B: Spark read from Volume (demo)
from pyspark.sql import functions as F

if FILE_FORMAT == "csv":
    df_raw = (
        spark.read
        .option("header", "true")
        .option("inferSchema", "true")
        .csv(SOURCE_VOLUME_PATH)
    )
elif FILE_FORMAT == "json":
    df_raw = spark.read.json(SOURCE_VOLUME_PATH)
else:
    raise ValueError(f"Unsupported format: {{FILE_FORMAT}}")

print(f"Read {{df_raw.count()}} rows from {{SOURCE_VOLUME_PATH}}")
df_raw.display()

# COMMAND ----------

# DBTITLE 1,Add metadata columns
df_bronze = (
    df_raw
    .withColumn("_ingestion_timestamp", F.current_timestamp())
    .withColumn("_source_file", F.input_file_name())
    .withColumn("_load_date", F.current_date())
)

# COMMAND ----------

# DBTITLE 1,Write to bronze Delta table
df_bronze.write.format("delta").mode("overwrite").saveAsTable(FULL_TABLE)
print(f"Successfully wrote {{df_bronze.count()}} rows to {{FULL_TABLE}}")

# COMMAND ----------

# DBTITLE 1,Verify
spark.sql(f"SELECT count(*) as row_count FROM {{FULL_TABLE}}").display()
'''

    elif config.pattern_id == "oracle_to_bronze":
        oc = config.oracle_config
        jdbc_url = oc.jdbc_url if oc else "jdbc:oracle:thin:@//<host>:<port>/<service>"
        src_table = oc.source_table if oc else "SCHEMA.TABLE"
        artifacts_path = config.artifacts_volume_path
        return header + f'''# DBTITLE 1,Configuration
CATALOG = "{config.catalog_name}"
TARGET_SCHEMA = "{config.target_schema}"
TABLE = "{config.target_table}"
FULL_TABLE = f"{{CATALOG}}.{{TARGET_SCHEMA}}.{{TABLE}}"

# Oracle JDBC -- use Databricks secrets in production
JDBC_URL = "{jdbc_url}"  # TODO: dbutils.secrets.get(scope="oracle", key="jdbc_url")
JDBC_USER = "<username>"  # TODO: dbutils.secrets.get(scope="oracle", key="user")
JDBC_PASSWORD = "<password>"  # TODO: dbutils.secrets.get(scope="oracle", key="password")
SOURCE_TABLE = "{src_table}"

# Demo mode: read mock data from artifacts volume
DEMO_MODE = True
MOCK_DATA_PATH = "{artifacts_path}/integration_packages/{{PACKAGE_ID}}/sample_data/"

# COMMAND ----------

# DBTITLE 1,Set up target schema
spark.sql(f"USE CATALOG {{CATALOG}}")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {{TARGET_SCHEMA}}")

# COMMAND ----------

# DBTITLE 1,Read source data
from pyspark.sql import functions as F

if DEMO_MODE:
    df_raw = (
        spark.read.option("header", "true").option("inferSchema", "true")
        .csv(MOCK_DATA_PATH)
    )
    print(f"[DEMO MODE] Read {{df_raw.count()}} rows from mock data")
else:
    # ---- PRODUCTION: JDBC read from Oracle ----
    df_raw = (
        spark.read.format("jdbc")
        .option("url", JDBC_URL).option("dbtable", SOURCE_TABLE)
        .option("user", JDBC_USER).option("password", JDBC_PASSWORD)
        .option("driver", "oracle.jdbc.driver.OracleDriver")
        .load()
    )
    print(f"Read {{df_raw.count()}} rows from Oracle {{SOURCE_TABLE}}")

df_raw.display()

# COMMAND ----------

# DBTITLE 1,Add metadata columns
df_bronze = (
    df_raw
    .withColumn("_ingestion_timestamp", F.current_timestamp())
    .withColumn("_source_system", F.lit("ORACLE_ERP"))
    .withColumn("_load_date", F.current_date())
)

# COMMAND ----------

# DBTITLE 1,Write to bronze Delta table
df_bronze.write.format("delta").mode("overwrite").saveAsTable(FULL_TABLE)
print(f"Successfully wrote {{df_bronze.count()}} rows to {{FULL_TABLE}}")

# COMMAND ----------

# DBTITLE 1,Verify
spark.sql(f"SELECT count(*) as row_count FROM {{FULL_TABLE}}").display()
'''

    return "# Pattern not recognized\n"


def generate_dq_notebook(config: IntegrationConfig) -> str:
    """Generate 02_data_quality_checks.py content."""
    header = _header("02 - Data Quality Checks", config)
    return header + f'''# DBTITLE 1,Configuration
CATALOG = "{config.catalog_name}"
SCHEMA = "{config.target_schema}"
TABLE = "{config.target_table}"
FULL_TABLE = f"{{CATALOG}}.{{TARGET_SCHEMA}}.{{TABLE}}"

# COMMAND ----------

# DBTITLE 1,Check 1: Table exists
try:
    spark.sql(f"DESCRIBE TABLE {{FULL_TABLE}}")
    print(f"PASS: Table {{FULL_TABLE}} exists")
except Exception as e:
    print(f"FAIL: Table {{FULL_TABLE}} does not exist — {{e}}")

# COMMAND ----------

# DBTITLE 1,Check 2: Table has rows
row_count = spark.sql(f"SELECT count(*) as cnt FROM {{FULL_TABLE}}").collect()[0]["cnt"]
if row_count > 0:
    print(f"PASS: Table has {{row_count}} rows")
else:
    print("FAIL: Table has 0 rows")

# COMMAND ----------

# DBTITLE 1,Check 3: Required metadata columns exist
columns = [c.name for c in spark.sql(f"DESCRIBE TABLE {{FULL_TABLE}}").collect()]
required_meta = ["_ingestion_timestamp", "_load_date"]
missing = [c for c in required_meta if c not in columns]
if not missing:
    print(f"PASS: All required metadata columns present")
else:
    print(f"FAIL: Missing columns: {{missing}}")

# COMMAND ----------

# DBTITLE 1,Check 4: Null counts
from pyspark.sql import functions as F

df = spark.table(FULL_TABLE)
print("=== Null counts per column ===")
for col_name in df.columns:
    null_count = df.where(F.col(col_name).isNull()).count()
    status = "OK" if null_count == 0 else f"WARNING: {{null_count}} nulls"
    print(f"  {{col_name}}: {{status}}")

# COMMAND ----------

# DBTITLE 1,Check 5: Duplicate check on first column
first_col = df.columns[0]
dup_count = df.count() - df.dropDuplicates([first_col]).count()
if dup_count == 0:
    print(f"PASS: No duplicates on {{first_col}}")
else:
    print(f"WARNING: {{dup_count}} duplicate(s) on {{first_col}}")

# COMMAND ----------

# DBTITLE 1,Summary
print("\n=== Data Quality Check Summary ===")
print(f"Table: {{FULL_TABLE}}")
print(f"Row count: {{row_count}}")
print(f"Column count: {{len(columns)}}")
print("Checks complete.")
'''


def generate_validation_notebook(config: IntegrationConfig) -> str:
    """Generate 03_demo_validation.py content."""
    header = _header("03 - Demo Validation", config)
    return header + f'''# DBTITLE 1,Configuration
CATALOG = "{config.catalog_name}"
SCHEMA = "{config.target_schema}"
TABLE = "{config.target_table}"
FULL_TABLE = f"{{CATALOG}}.{{TARGET_SCHEMA}}.{{TABLE}}"
SAMPLE_DATA_PATH = "{config.artifacts_volume_path}/integration_packages/{{PACKAGE_ID}}/sample_data/"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 1: Inspect sample data

# COMMAND ----------

# DBTITLE 1,Read and display sample data
df_sample = (
    spark.read
    .option("header", "true")
    .option("inferSchema", "true")
    .csv(SAMPLE_DATA_PATH)
)
print(f"Sample records: {{df_sample.count()}}")
df_sample.display()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 2: Query bronze table

# COMMAND ----------

# DBTITLE 1,Show bronze table contents
try:
    df_bronze = spark.table(FULL_TABLE)
    print(f"Bronze table row count: {{df_bronze.count()}}")
    df_bronze.display()
except Exception as e:
    print(f"Bronze table not found. Run 01_ingest_to_bronze first. Error: {{e}}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 3: Run quality checks

# COMMAND ----------

# DBTITLE 1,Quick quality validation
from pyspark.sql import functions as F

try:
    df = spark.table(FULL_TABLE)
    checks = {{}}
    checks["table_exists"] = True
    checks["row_count"] = df.count()
    checks["has_rows"] = checks["row_count"] > 0
    checks["has_ingestion_ts"] = "_ingestion_timestamp" in df.columns
    checks["has_load_date"] = "_load_date" in df.columns

    print("=== Validation Results ===")
    all_pass = True
    for check, result in checks.items():
        status = "PASS" if result else "FAIL"
        if not result:
            all_pass = False
        print(f"  {{check}}: {{status}} ({{result}})")

    print(f"\nOverall: {{\"ALL CHECKS PASSED\" if all_pass else \"SOME CHECKS FAILED\"}}")
except Exception as e:
    print(f"Validation failed: {{e}}")
'''
